server:
  port: 8080
spring:
  application:
    name: cloudclient
  cloud:
   config:
     uri: http://localhost:8888
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
